import {
  AIDifficultyConfig,
  ArenaColorTheme,
  CampaignChapter,
  CampaignLevelConfig,
  DifficultyLevel,
} from '../types/game';

export const ARENA_WIDTH = 960;
export const ARENA_HEIGHT = 600;

export const MECH_RADIUS = 26;
export const BASE_HP = 100;
export const MAX_LIVES = 3;

export const BASE_SPEED = 210; // px per second
export const SPEED_BOOST_SPEED = 300;
export const SPEED_BOOST_DURATION = 6.0; // seconds

export const ATTACK_COOLDOWN = 0.42; // seconds
export const ATTACK_DURATION = 0.16; // visual slash window
export const ATTACK_REACH = 74; // range from center
export const ATTACK_ARC = Math.PI * 0.72; // arc sweep
export const BASE_ATTACK_DAMAGE = 18;
export const POWER_ATTACK_DAMAGE = 36;

export const DASH_SPEED = 620;
export const DASH_DURATION = 0.22;
export const DASH_COOLDOWN = 1.35;
export const DASH_INVULNERABLE_TIME = 0.18;

export const HIT_STUN_DURATION = 0.16;
export const INVULNERABLE_AFTER_HIT = 0.35;

export const POWER_UP_DURATION = 14; // despawn timer
export const POWER_UP_SPAWN_INTERVAL_MIN = 7;
export const POWER_UP_SPAWN_INTERVAL_MAX = 12;

export const AI_DIFFICULTIES: Record<DifficultyLevel, AIDifficultyConfig> = {
  NORMAL: {
    reactionDelay: 0.38,
    moveSpeedMultiplier: 0.88,
    attackRange: 66,
    attackProbability: 0.50,
    dodgeProbability: 0.22,
    dashProbability: 0.18,
    counterProbability: 0.20,
    powerUpPriority: 0.40,
    predictionStrength: 0.10,
    hazardAwareness: 0.60,
    retreatThreshold: 20,
    strafeTendency: 0.30,
    personality: 'BALANCED',
    repositionChance: 0.25,
    feintChance: 0.10,
    description: 'Learn the fundamentals of combat with noticeable reaction windows.',
  },
  MEDIUM: {
    reactionDelay: 0.24,
    moveSpeedMultiplier: 0.96,
    attackRange: 70,
    attackProbability: 0.68,
    dodgeProbability: 0.45,
    dashProbability: 0.40,
    counterProbability: 0.45,
    powerUpPriority: 0.68,
    predictionStrength: 0.35,
    hazardAwareness: 0.80,
    retreatThreshold: 26,
    strafeTendency: 0.50,
    personality: 'BALANCED',
    repositionChance: 0.35,
    feintChance: 0.20,
    description: 'Tactical opponent with steady reflexes and counter-attacks.',
  },
  HARD: {
    reactionDelay: 0.14,
    moveSpeedMultiplier: 1.02,
    attackRange: 74,
    attackProbability: 0.82,
    dodgeProbability: 0.65,
    dashProbability: 0.62,
    counterProbability: 0.68,
    powerUpPriority: 0.86,
    predictionStrength: 0.58,
    hazardAwareness: 0.92,
    retreatThreshold: 32,
    strafeTendency: 0.68,
    personality: 'FLANKER',
    repositionChance: 0.45,
    feintChance: 0.30,
    description: 'Aggressive pacing, agile dodging, and decisive counters.',
  },
  EXTREME_HARD: {
    reactionDelay: 0.08,
    moveSpeedMultiplier: 1.06,
    attackRange: 76,
    attackProbability: 0.90,
    dodgeProbability: 0.78,
    dashProbability: 0.76,
    counterProbability: 0.82,
    powerUpPriority: 0.94,
    predictionStrength: 0.76,
    hazardAwareness: 0.96,
    retreatThreshold: 36,
    strafeTendency: 0.80,
    personality: 'BRAWLER',
    repositionChance: 0.55,
    feintChance: 0.38,
    description: 'Elite sentinel with razor-sharp evasion and lethal punish windows.',
  },
  HARDCORE: {
    reactionDelay: 0.045,
    moveSpeedMultiplier: 1.10,
    attackRange: 76,
    attackProbability: 0.95,
    dodgeProbability: 0.86,
    dashProbability: 0.84,
    counterProbability: 0.90,
    powerUpPriority: 0.98,
    predictionStrength: 0.88,
    hazardAwareness: 0.99,
    retreatThreshold: 40,
    strafeTendency: 0.88,
    personality: 'APEX',
    repositionChance: 0.65,
    feintChance: 0.45,
    description: 'Peak synaptic speed with master spacing. Only elite pilots survive.',
  },
};

export const CAMPAIGN_CHAPTERS: CampaignChapter[] = [
  {
    id: 1,
    title: 'CHAPTER 1: AWAKENING',
    subtitle: 'Levels 1–10 • Easy to Normal',
    levelRange: [1, 10],
    theme: 'CYAN_MATRIX',
    description: 'Master locomotion, slash timing, dash invulnerability, and take down the Prototype Mini-Boss.',
  },
  {
    id: 2,
    title: 'CHAPTER 2: RISING THREAT',
    subtitle: 'Levels 11–20 • Normal to Medium',
    levelRange: [11, 20],
    theme: 'NEON_PURPLE',
    description: 'Moving laser barriers and smarter AI opponents contest power-ups, culminating in NOVA STRIKER.',
  },
  {
    id: 3,
    title: 'CHAPTER 3: WAR MACHINE',
    subtitle: 'Levels 21–30 • Medium to Hard',
    levelRange: [21, 30],
    theme: 'CRIMSON_FORGE',
    description: 'Heavy industrial battlefields with crushing hazards and tactical brawling against NOVA WARLORD.',
  },
  {
    id: 4,
    title: 'CHAPTER 4: CYBER SIEGE',
    subtitle: 'Levels 31–40 • Hard to Extreme Hard',
    levelRange: [31, 40],
    theme: 'EMERALD_NEXUS',
    description: 'Multi-hazard grids, rapid counter-dashes, and intense tactical pressure against the Cyber Titan.',
  },
  {
    id: 5,
    title: 'CHAPTER 5: APEX OVERLORD',
    subtitle: 'Levels 41–50 • Extreme to Hardcore',
    levelRange: [41, 50],
    theme: 'GOLD_CORE',
    description: 'The pinnacle of cybernetic evolution. Face the sentient God-Code and conquer APEX NOVA.',
  },
];

export const CAMPAIGN_LEVELS: CampaignLevelConfig[] = [
  // ================= CHAPTER 1: AWAKENING (1–10) =================
  {
    level: 1,
    chapter: 1,
    chapterTitle: 'AWAKENING',
    title: 'Level 1: System Boot',
    subtitle: 'Cadet Proving Grounds',
    difficulty: 'NORMAL',
    hazardsEnabled: false,
    hazardTypes: [],
    arenaColorTheme: 'CYAN_MATRIX',
    arenaLayout: 'OPEN_GAUNTLET',
    briefing: 'Basic combat simulation. NOVA AI running in calibration mode with sluggish servo response. Get comfortable with movement and dashing.',
  },
  {
    level: 2,
    chapter: 1,
    chapterTitle: 'AWAKENING',
    title: 'Level 2: Target Acquisition',
    subtitle: 'Sub-Grid Alpha',
    difficulty: 'NORMAL',
    hazardsEnabled: false,
    hazardTypes: [],
    arenaColorTheme: 'CYAN_MATRIX',
    arenaLayout: 'STANDARD',
    briefing: 'NOVA activates primary tracking algorithms. Practice timing your plasma blade slash when inside strike reach.',
  },
  {
    level: 3,
    chapter: 1,
    chapterTitle: 'AWAKENING',
    title: 'Level 3: Servo Calibration',
    subtitle: 'Tactical Quadrant',
    difficulty: 'NORMAL',
    hazardsEnabled: false,
    hazardTypes: [],
    arenaColorTheme: 'CYAN_MATRIX',
    arenaLayout: 'PILLARS_4',
    briefing: 'Four cyber pillars installed. Use physical barriers to break line-of-sight and flank your opponent.',
  },
  {
    level: 4,
    chapter: 1,
    chapterTitle: 'AWAKENING',
    title: 'Level 4: Velocity Check',
    subtitle: 'Vector Corridor',
    difficulty: 'NORMAL',
    hazardsEnabled: false,
    hazardTypes: [],
    arenaColorTheme: 'CYAN_MATRIX',
    arenaLayout: 'TWIN_BUNKERS',
    briefing: 'NOVA increases forward sprint speed. Use Dash [G] to phase through incoming strikes without taking damage.',
  },
  {
    level: 5,
    chapter: 1,
    chapterTitle: 'AWAKENING',
    title: 'Level 5: Power Surge',
    subtitle: 'Generator Bay',
    difficulty: 'NORMAL',
    hazardsEnabled: false,
    hazardTypes: [],
    arenaColorTheme: 'CYAN_MATRIX',
    arenaLayout: 'STANDARD',
    briefing: 'Arena telemetry now spawns tactical power-up capsules (Shield, 2x Damage, Speed Boost). Race to secure them first!',
  },
  {
    level: 6,
    chapter: 1,
    chapterTitle: 'AWAKENING',
    title: 'Level 6: Faulty Flooring',
    subtitle: 'Fracture Bay',
    difficulty: 'NORMAL',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE'],
    arenaColorTheme: 'CYAN_MATRIX',
    arenaLayout: 'STANDARD',
    briefing: 'Structural warning! Unstable floor tiles in the center will flash yellow before collapsing into the cyber void.',
  },
  {
    level: 7,
    chapter: 1,
    chapterTitle: 'AWAKENING',
    title: 'Level 7: Evasion Drill',
    subtitle: 'Reflex Depot',
    difficulty: 'NORMAL',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE'],
    arenaColorTheme: 'CYAN_MATRIX',
    arenaLayout: 'PILLARS_4',
    briefing: 'NOVA attempts basic dodge maneuvers. Lure your opponent near collapsing zones for positional advantage.',
  },
  {
    level: 8,
    chapter: 1,
    chapterTitle: 'AWAKENING',
    title: 'Level 8: Static Discharge',
    subtitle: 'Tesla Verge',
    difficulty: 'NORMAL',
    hazardsEnabled: true,
    hazardTypes: ['ELECTRIC'],
    arenaColorTheme: 'CYAN_MATRIX',
    arenaLayout: 'STANDARD',
    briefing: 'High-voltage Tesla nodes installed in the upper and lower arena lanes. Steer clear when they charge up.',
  },
  {
    level: 9,
    chapter: 1,
    chapterTitle: 'AWAKENING',
    title: 'Level 9: Crossfire Prep',
    subtitle: 'Perimeter Bastion',
    difficulty: 'NORMAL',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'ELECTRIC'],
    arenaColorTheme: 'CYAN_MATRIX',
    arenaLayout: 'TWIN_BUNKERS',
    briefing: 'Both electric pylons and collapsing tiles are active. NOVA combat subroutines are fully warmed up.',
  },
  {
    level: 10,
    chapter: 1,
    chapterTitle: 'AWAKENING',
    title: 'Level 10: Prototype V1',
    subtitle: 'Sandbox Core • MINI BOSS',
    difficulty: 'NORMAL',
    isBoss: true,
    bossTier: 'MINI_BOSS',
    bossName: 'NOVA MK-I',
    hazardsEnabled: true,
    hazardTypes: ['ELECTRIC', 'COLLAPSE'],
    arenaColorTheme: 'CYAN_MATRIX',
    arenaLayout: 'PILLARS_4',
    briefing: 'MINI BOSS ENGAGEMENT! NOVA Prototype MK-I enters the arena with aggressive pursuit and rapid dash counters. Defeat the Boss to unlock Chapter 2!',
  },

  // ================= CHAPTER 2: RISING THREAT (11–20) =================
  {
    level: 11,
    chapter: 2,
    chapterTitle: 'RISING THREAT',
    title: 'Level 11: Neon Foundry',
    subtitle: 'Sub-Station Delta',
    difficulty: 'NORMAL',
    hazardsEnabled: true,
    hazardTypes: ['BARRIER'],
    arenaColorTheme: 'NEON_PURPLE',
    arenaLayout: 'STANDARD',
    briefing: 'Welcome to the Neon Foundry. Moving laser barriers sweep the central combat floor. Dash through them with invulnerability!',
  },
  {
    level: 12,
    chapter: 2,
    chapterTitle: 'RISING THREAT',
    title: 'Level 12: Beam Hall Alpha',
    subtitle: 'Diffraction Chasm',
    difficulty: 'NORMAL',
    hazardsEnabled: true,
    hazardTypes: ['BARRIER'],
    arenaColorTheme: 'NEON_PURPLE',
    arenaLayout: 'CROSS_CORRIDOR',
    briefing: 'Vertical tech baffles channel combat into tight choke points while laser barriers restrict lateral movement.',
  },
  {
    level: 13,
    chapter: 2,
    chapterTitle: 'RISING THREAT',
    title: 'Level 13: Pulse Junction',
    subtitle: 'Relay Station 9',
    difficulty: 'MEDIUM',
    hazardsEnabled: true,
    hazardTypes: ['ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'NEON_PURPLE',
    arenaLayout: 'PILLARS_4',
    briefing: 'NOVA AI upgraded to Medium tier! It now actively predicts your movement trajectory and hunts down repair items.',
  },
  {
    level: 14,
    chapter: 2,
    chapterTitle: 'RISING THREAT',
    title: 'Level 14: Unstable Core',
    subtitle: 'Decay Pit',
    difficulty: 'MEDIUM',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE'],
    arenaColorTheme: 'NEON_PURPLE',
    arenaLayout: 'TWIN_BUNKERS',
    briefing: 'Fast collapsing cycles. The floor will restore and collapse at irregular intervals. Don’t get trapped!',
  },
  {
    level: 15,
    chapter: 2,
    chapterTitle: 'RISING THREAT',
    title: 'Level 15: Twin Nodes',
    subtitle: 'Resonance Chamber',
    difficulty: 'MEDIUM',
    hazardsEnabled: true,
    hazardTypes: ['ELECTRIC', 'COLLAPSE'],
    arenaColorTheme: 'NEON_PURPLE',
    arenaLayout: 'OCTAGON',
    briefing: 'Octagon arena formation. Angled perimeter barriers restrict retreat corners. Maintain central spatial dominance.',
  },
  {
    level: 16,
    chapter: 2,
    chapterTitle: 'RISING THREAT',
    title: 'Level 16: Silicon Ridge',
    subtitle: 'Overclocked Outpost',
    difficulty: 'MEDIUM',
    hazardsEnabled: true,
    hazardTypes: ['BARRIER'],
    arenaColorTheme: 'NEON_PURPLE',
    arenaLayout: 'STANDARD',
    briefing: 'NOVA begins executing tactical retreats when its hull health falls below critical threshold. Press the advantage!',
  },
  {
    level: 17,
    chapter: 2,
    chapterTitle: 'RISING THREAT',
    title: 'Level 17: Fissure Zone',
    subtitle: 'Rupture Sector',
    difficulty: 'MEDIUM',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'BARRIER'],
    arenaColorTheme: 'NEON_PURPLE',
    arenaLayout: 'PILLARS_4',
    briefing: 'Moving energy barriers sweep directly across the collapsing floor plates. Precision dash timing is vital.',
  },
  {
    level: 18,
    chapter: 2,
    chapterTitle: 'RISING THREAT',
    title: 'Level 18: Deadlock Arena',
    subtitle: 'Sub-Station Zeta',
    difficulty: 'MEDIUM',
    hazardsEnabled: true,
    hazardTypes: ['ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'NEON_PURPLE',
    arenaLayout: 'CROSS_CORRIDOR',
    briefing: 'Double corridor crossfire. NOVA uses wall geometry to bounce out of reach when taking heavy damage.',
  },
  {
    level: 19,
    chapter: 2,
    chapterTitle: 'RISING THREAT',
    title: 'Level 19: High Voltage Trench',
    subtitle: 'Conduit Deep',
    difficulty: 'MEDIUM',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'NEON_PURPLE',
    arenaLayout: 'FORTRESS',
    briefing: 'All three hazard categories activated simultaneously. Fortified bunker blocks offer temporary sanctuary from lasers.',
  },
  {
    level: 20,
    chapter: 2,
    chapterTitle: 'RISING THREAT',
    title: 'Level 20: Tempest Striker',
    subtitle: 'Storm Core • CHAPTER BOSS',
    difficulty: 'MEDIUM',
    isBoss: true,
    bossTier: 'BOSS',
    bossName: 'NOVA STRIKER',
    hazardsEnabled: true,
    hazardTypes: ['ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'NEON_PURPLE',
    arenaLayout: 'OCTAGON',
    briefing: 'CHAPTER 2 BOSS! NOVA STRIKER is outfitted with high-output thrusters. It rapidly contests drops and executes quick dashing counter-strikes!',
  },

  // ================= CHAPTER 3: WAR MACHINE (21–30) =================
  {
    level: 21,
    chapter: 3,
    chapterTitle: 'WAR MACHINE',
    title: 'Level 21: Iron Crucible',
    subtitle: 'Smelting Works',
    difficulty: 'MEDIUM',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE'],
    arenaColorTheme: 'CRIMSON_FORGE',
    arenaLayout: 'FORTRESS',
    briefing: 'Welcome to the Crimson Forge. Molten heat and heavy blast doors. NOVA attacks with reinforced aggression.',
  },
  {
    level: 22,
    chapter: 3,
    chapterTitle: 'WAR MACHINE',
    title: 'Level 22: Molten Trench',
    subtitle: 'Forge Sector 4',
    difficulty: 'HARD',
    hazardsEnabled: true,
    hazardTypes: ['BARRIER'],
    arenaColorTheme: 'CRIMSON_FORGE',
    arenaLayout: 'STANDARD',
    briefing: 'AI reaches HARD difficulty! NOVA synaptic response accelerates to sub-150ms. Anticipate incoming attacks before they land.',
  },
  {
    level: 23,
    chapter: 3,
    chapterTitle: 'WAR MACHINE',
    title: 'Level 23: Combustion Ring',
    subtitle: 'Burn Chamber',
    difficulty: 'HARD',
    hazardsEnabled: true,
    hazardTypes: ['ELECTRIC'],
    arenaColorTheme: 'CRIMSON_FORGE',
    arenaLayout: 'OCTAGON',
    briefing: 'High-current Tesla nodes operate on shorter cooldowns. NOVA will attempt to push or knock you into live currents.',
  },
  {
    level: 24,
    chapter: 3,
    chapterTitle: 'WAR MACHINE',
    title: 'Level 24: Armor Breaker',
    subtitle: 'Anvil Bay',
    difficulty: 'HARD',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'BARRIER'],
    arenaColorTheme: 'CRIMSON_FORGE',
    arenaLayout: 'PILLARS_4',
    briefing: 'NOVA prioritizes 2x Power Attack power-ups above all else. Intercept them or face devastating 36-damage critical slashes.',
  },
  {
    level: 25,
    chapter: 3,
    chapterTitle: 'WAR MACHINE',
    title: 'Level 25: Plasma Conduit',
    subtitle: 'Redline Works',
    difficulty: 'HARD',
    hazardsEnabled: true,
    hazardTypes: ['ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'CRIMSON_FORGE',
    arenaLayout: 'CROSS_CORRIDOR',
    briefing: 'Tightly confined central alleys. Whichever mech controls the middle controls the power-up spawn zone.',
  },
  {
    level: 26,
    chapter: 3,
    chapterTitle: 'WAR MACHINE',
    title: 'Level 26: Heavy Metal',
    subtitle: 'Foundry Floor',
    difficulty: 'HARD',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'ELECTRIC'],
    arenaColorTheme: 'CRIMSON_FORGE',
    arenaLayout: 'TWIN_BUNKERS',
    briefing: 'Heavy bunker obstacles split the combat zone. Use dash curving to cut off NOVA’s retreat angles.',
  },
  {
    level: 27,
    chapter: 3,
    chapterTitle: 'WAR MACHINE',
    title: 'Level 27: Slag Corridor',
    subtitle: 'Magma Vent',
    difficulty: 'HARD',
    hazardsEnabled: true,
    hazardTypes: ['BARRIER'],
    arenaColorTheme: 'CRIMSON_FORGE',
    arenaLayout: 'PERIMETER_WALLS',
    briefing: 'Perimeter baffles force circular combat flow. Moving lasers sweep along the inner circuit.',
  },
  {
    level: 28,
    chapter: 3,
    chapterTitle: 'WAR MACHINE',
    title: 'Level 28: Kinetic Gauntlet',
    subtitle: 'Impact Zone',
    difficulty: 'HARD',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'BARRIER'],
    arenaColorTheme: 'CRIMSON_FORGE',
    arenaLayout: 'FORTRESS',
    briefing: 'NOVA displays sophisticated strafing patterns, circling just outside your strike range to bait out missed attacks.',
  },
  {
    level: 29,
    chapter: 3,
    chapterTitle: 'WAR MACHINE',
    title: 'Level 29: Siege Deck',
    subtitle: 'Barrage Redoubt',
    difficulty: 'HARD',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'CRIMSON_FORGE',
    arenaLayout: 'PILLARS_4',
    briefing: 'Final security detachment before the Dreadnought Bastion. Triple hazards active under high-stress combat conditions.',
  },
  {
    level: 30,
    chapter: 3,
    chapterTitle: 'WAR MACHINE',
    title: 'Level 30: Iron Warlord',
    subtitle: 'Dreadnought Bastion • CHAPTER BOSS',
    difficulty: 'HARD',
    isBoss: true,
    bossTier: 'BOSS',
    bossName: 'NOVA WARLORD',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'CRIMSON_FORGE',
    arenaLayout: 'FORTRESS',
    briefing: 'CHAPTER 3 BOSS! NOVA WARLORD commands superior tactical dominance. It mercilessly snatches power-ups and executes crushing counter-slashes!',
  },

  // ================= CHAPTER 4: CYBER SIEGE (31–40) =================
  {
    level: 31,
    chapter: 4,
    chapterTitle: 'CYBER SIEGE',
    title: 'Level 31: Neural Matrix',
    subtitle: 'Synapse Node',
    difficulty: 'HARD',
    hazardsEnabled: true,
    hazardTypes: ['ELECTRIC'],
    arenaColorTheme: 'EMERALD_NEXUS',
    arenaLayout: 'STANDARD',
    briefing: 'Entering the Emerald Nexus. The cyber grid pulses with overclocked data flow. AI prediction models are running at maximum capacity.',
  },
  {
    level: 32,
    chapter: 4,
    chapterTitle: 'CYBER SIEGE',
    title: 'Level 32: Quantum Collapse',
    subtitle: 'Zero Grid',
    difficulty: 'HARD',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE'],
    arenaColorTheme: 'EMERALD_NEXUS',
    arenaLayout: 'OCTAGON',
    briefing: 'Floor tiles collapse rapidly with minimal warning. Stay light on your servos and never remain stationary.',
  },
  {
    level: 33,
    chapter: 4,
    chapterTitle: 'CYBER SIEGE',
    title: 'Level 33: Laser Web',
    subtitle: 'Diffraction Chamber',
    difficulty: 'EXTREME_HARD',
    hazardsEnabled: true,
    hazardTypes: ['BARRIER'],
    arenaColorTheme: 'EMERALD_NEXUS',
    arenaLayout: 'CROSS_CORRIDOR',
    briefing: 'Threat level escalates to EXTREME HARD! NOVA reaction delay drops below 80ms. Feints and precision dash dodges are required.',
  },
  {
    level: 34,
    chapter: 4,
    chapterTitle: 'CYBER SIEGE',
    title: 'Level 34: Overdrive Protocol',
    subtitle: 'Hyper-Clock Lab',
    difficulty: 'EXTREME_HARD',
    hazardsEnabled: true,
    hazardTypes: ['ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'EMERALD_NEXUS',
    arenaLayout: 'PILLARS_4',
    briefing: 'NOVA predicts your movement vectors with 80% accuracy. Break predictable patterns by abruptly reversing your joystick direction.',
  },
  {
    level: 35,
    chapter: 4,
    chapterTitle: 'CYBER SIEGE',
    title: 'Level 35: Memory Leak',
    subtitle: 'Decay Cache',
    difficulty: 'EXTREME_HARD',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'BARRIER'],
    arenaColorTheme: 'EMERALD_NEXUS',
    arenaLayout: 'TWIN_BUNKERS',
    briefing: 'NOVA will dash through barriers using its own invulnerability frames to corner VEX against the void.',
  },
  {
    level: 36,
    chapter: 4,
    chapterTitle: 'CYBER SIEGE',
    title: 'Level 36: Cipher Bastion',
    subtitle: 'Encrypted Citadel',
    difficulty: 'EXTREME_HARD',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'ELECTRIC'],
    arenaColorTheme: 'EMERALD_NEXUS',
    arenaLayout: 'FORTRESS',
    briefing: 'Multiple cover pillars. NOVA hides behind obstacles to recharge its dash before springing out with lethal strikes.',
  },
  {
    level: 37,
    chapter: 4,
    chapterTitle: 'CYBER SIEGE',
    title: 'Level 37: Phase Shift',
    subtitle: 'Disruption Field',
    difficulty: 'EXTREME_HARD',
    hazardsEnabled: true,
    hazardTypes: ['ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'EMERALD_NEXUS',
    arenaLayout: 'PERIMETER_WALLS',
    briefing: 'High-speed perimeter combat. Secure the Shield power-up to absorb a catastrophic blow.',
  },
  {
    level: 38,
    chapter: 4,
    chapterTitle: 'CYBER SIEGE',
    title: 'Level 38: Recursion Pit',
    subtitle: 'Echo Chamber',
    difficulty: 'EXTREME_HARD',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'BARRIER'],
    arenaColorTheme: 'EMERALD_NEXUS',
    arenaLayout: 'OCTAGON',
    briefing: 'Tight octagon ring. Missed slashes leave you vulnerable for 160ms—punished immediately by high-tier AI.',
  },
  {
    level: 39,
    chapter: 4,
    chapterTitle: 'CYBER SIEGE',
    title: 'Level 39: Critical Threshold',
    subtitle: 'Singularity Gate',
    difficulty: 'EXTREME_HARD',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'EMERALD_NEXUS',
    arenaLayout: 'FORTRESS',
    briefing: 'Full-spectrum hazard interference. NOVA operates at peak military overclocking. Stand your ground, Pilot!',
  },
  {
    level: 40,
    chapter: 4,
    chapterTitle: 'CYBER SIEGE',
    title: 'Level 40: Cyber Titan',
    subtitle: 'Titan Monolith • MAJOR BOSS',
    difficulty: 'EXTREME_HARD',
    isBoss: true,
    bossTier: 'MAJOR_BOSS',
    bossName: 'NOVA TITAN',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'EMERALD_NEXUS',
    arenaLayout: 'OCTAGON',
    briefing: 'MAJOR BOSS BATTLE! NOVA TITAN commands absolute battlefield awareness. It anticipates dashes and punishes overextensions without remorse!',
  },

  // ================= CHAPTER 5: APEX OVERLORD (41–50) =================
  {
    level: 41,
    chapter: 5,
    chapterTitle: 'APEX OVERLORD',
    title: 'Level 41: Event Horizon',
    subtitle: 'Void Threshold',
    difficulty: 'EXTREME_HARD',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE'],
    arenaColorTheme: 'OBSIDIAN_VOID',
    arenaLayout: 'STANDARD',
    briefing: 'You have entered the Apex Domain. The void beckons. Every strike must be deliberate; every dash calculated.',
  },
  {
    level: 42,
    chapter: 5,
    chapterTitle: 'APEX OVERLORD',
    title: 'Level 42: Antimatter Grid',
    subtitle: 'Dark Matter Vault',
    difficulty: 'EXTREME_HARD',
    hazardsEnabled: true,
    hazardTypes: ['ELECTRIC'],
    arenaColorTheme: 'OBSIDIAN_VOID',
    arenaLayout: 'PILLARS_4',
    briefing: 'Pulsing dark matter currents. NOVA maneuvers with razor-thin margins around active hazards.',
  },
  {
    level: 43,
    chapter: 5,
    chapterTitle: 'APEX OVERLORD',
    title: 'Level 43: Chrono Rift',
    subtitle: 'Prism of Doom',
    difficulty: 'HARDCORE',
    hazardsEnabled: true,
    hazardTypes: ['BARRIER'],
    arenaColorTheme: 'GOLD_CORE',
    arenaLayout: 'CROSS_CORRIDOR',
    briefing: 'HARDCORE TIER UNLOCKED! AI synaptic lag reduced to 40ms. Flawless execution is the only path to survival.',
  },
  {
    level: 44,
    chapter: 5,
    chapterTitle: 'APEX OVERLORD',
    title: 'Level 44: Neural Cascade',
    subtitle: 'Apex Synapse',
    difficulty: 'HARDCORE',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'ELECTRIC'],
    arenaColorTheme: 'GOLD_CORE',
    arenaLayout: 'TWIN_BUNKERS',
    briefing: 'Power-ups spawn and are instantly contested. Never let NOVA acquire a 2x Power Attack buff.',
  },
  {
    level: 45,
    chapter: 5,
    chapterTitle: 'APEX OVERLORD',
    title: 'Level 45: Absolute Zero',
    subtitle: 'Cryo Singularity',
    difficulty: 'HARDCORE',
    hazardsEnabled: true,
    hazardTypes: ['ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'OBSIDIAN_VOID',
    arenaLayout: 'OCTAGON',
    briefing: 'NOVA chains dashes into sudden directional strikes. Read its approach angle and dodge with precision.',
  },
  {
    level: 46,
    chapter: 5,
    chapterTitle: 'APEX OVERLORD',
    title: 'Level 46: Oblivion Spire',
    subtitle: 'Ascent of Ruin',
    difficulty: 'HARDCORE',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'BARRIER'],
    arenaColorTheme: 'GOLD_CORE',
    arenaLayout: 'FORTRESS',
    briefing: 'A fortified gauntlet. Use obstacles to deflect NOVA’s forward momentum and counter-attack from its blind side.',
  },
  {
    level: 47,
    chapter: 5,
    chapterTitle: 'APEX OVERLORD',
    title: 'Level 47: Synaptic Inferno',
    subtitle: 'Cortex Chamber',
    difficulty: 'HARDCORE',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'OBSIDIAN_VOID',
    arenaLayout: 'PERIMETER_WALLS',
    briefing: 'Extreme multi-hazard density. The arena itself is a deadly weapon. Stay centered and master the rhythm of battle.',
  },
  {
    level: 48,
    chapter: 5,
    chapterTitle: 'APEX OVERLORD',
    title: 'Level 48: God Code',
    subtitle: 'Architect Sanctorum',
    difficulty: 'HARDCORE',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'GOLD_CORE',
    arenaLayout: 'PILLARS_4',
    briefing: 'The sentience algorithms reach singularity. NOVA anticipates 95% of attacks. Perfect your feints and dash-cancel strikes.',
  },
  {
    level: 49,
    chapter: 5,
    chapterTitle: 'APEX OVERLORD',
    title: 'Level 49: The Crucible of Kings',
    subtitle: 'Penultimate Gauntlet',
    difficulty: 'HARDCORE',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'OBSIDIAN_VOID',
    arenaLayout: 'FORTRESS',
    briefing: 'One battle remains before the Throne. Defeat NOVA’s royal vanguard to claim your audience with the Apex Overlord.',
  },
  {
    level: 50,
    chapter: 5,
    chapterTitle: 'APEX OVERLORD',
    title: 'Level 50: Apex Overlord',
    subtitle: 'Throne of the Singularity • FINAL BOSS',
    difficulty: 'HARDCORE',
    isBoss: true,
    bossTier: 'FINAL_BOSS',
    bossName: 'APEX NOVA',
    hazardsEnabled: true,
    hazardTypes: ['COLLAPSE', 'ELECTRIC', 'BARRIER'],
    arenaColorTheme: 'GOLD_CORE',
    arenaLayout: 'OCTAGON',
    briefing: 'THE FINAL SHOWDOWN! APEX NOVA has achieved true digital omniscience. Sub-40ms reactions, ruthless aggression, and godlike evasion. Slay the Overlord and become the Legend of Mecha Clash!',
  },
];
